# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a5f6b79e-6dbc-4601-971b-a36a3863ee8d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-eaf15b8a-a523-4990-a5db-c0e9c3f7e455".device = "/dev/disk/by-uuid/eaf15b8a-a523-4990-a5db-c0e9c3f7e455";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2221-C937";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9c75e67d-6e87-4a32-89a5-b8b3eb115861"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
